# appveyor.yml

install:
    - C:\\Python35\\python.exe --version
    - C:\\Python35\\python.exe -m pip install pyinstaller
    - C:\\Python35\\python.exe -m pip install Pillow
    
    # check that dependencies installed.
    - C:\\Python35\\python.exe -c "from PIL import Image, ImageDraw, ImageOps"
    - C:\\Python35\\python.exe -c "from tkinter import ttk"

build_script:
    - C:\Python35\Scripts\pyinstaller.exe mmagedit.py --windowed -i "icon.ico" --paths=. --hidden-import mmdata --add-data="icon.png;."
    - move dist\\mmagedit mmagedit
    - move examples mmagedit

after_build:
    - C:\\Python35\\python.exe mmagedit.py --help
    - C:\\Python35\\python.exe mmagedit.py --deps
    - mmagedit\\mmagedit.exe --help
    - mmagedit\\mmagedit.exe --deps

artifacts:
    - path: mmagedit