# appveyor.yml

image:
  - Visual Studio 2019

cache:
  - C:\Tools\vcpkg\

install:
    # get python3.9
    - appveyor DownloadFile https://www.python.org/ftp/python/3.8.8/python-3.8.8-embed-amd64.zip -Filename python38_64.zip
    - 7z e -y -opython38 python38_64.zip
    - C:\\Python35\\python.exe --version
    - C:\\Python35\\python.exe -m pip install pyinstaller
    - C:\\Python35\\python.exe -m pip install Pillow
    # check that dependencies installed.
    - C:\\Python35\\python.exe -c "from PIL import Image, ImageDraw, ImageOps"
    - C:\\Python35\\python.exe -c "from tkinter import ttk"
    - SET PATH=%PATH%;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
    # (for 32 bit -- also maybe need to add -m32 to the build?)
    #- SET PATH=%PATH%;C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin

build_script:
    - copy python38\* libmmagedit
    - cd libmmagedit
    - g++ --version
    - dir
    # build libmmagedit.dll
    - g++ -shared mmagedit.cpp -static-libgcc -static-libstdc++ -o libmmagedit.dll -L. -I. -lpython38 -DLOCAL_PYTHON_H
    # build mmagedit test
    - g++ mmagedit.cpp -static-libgcc -static-libstdc++ -o mmagedit.exe -L. -I. -lpython38 -DLOCAL_PYTHON_H -DMAIN
    - mmagedit.exe ../mmagedit.py
    - dir
    - cd ..
    - C:\Python35\Scripts\pyinstaller.exe mmagedit.py --windowed -i "icon.ico" --paths=. --hidden-import mmdata --add-data="icon.png;."
    - move dist\\mmagedit mmagedit
    - move examples mmagedit
    - cd mmagedit
    - mkdir libmmagedit
    - cd ..
    - move libmmagedit\libmmagedit.dll mmagedit\libmmagedit
    - move python38\* mmagedit\libmmagedit

after_build:
    - C:\\Python35\\python.exe mmagedit.py --help
    - C:\\Python35\\python.exe mmagedit.py --deps
    - mmagedit\\mmagedit.exe --help
    - mmagedit\\mmagedit.exe --deps

artifacts:
    - path: mmagedit